name: workflow.yml
on:
 push:
   branches:
     - main
jobs:
  push_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_repo
        uses: actions/checkout@v3
      - name: installer_jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: check_java
        run: java --version
      - name: maven
        run: mvn clean install
