name: workflow.yml
on:
 push:
   branches:
     - main
jobs:
  push_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_repo
        uses: actions/checkout@v4
      - name: installer_jdk
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: check_java
        run: java --version
      - name: java installer
        run: echo "java installer"
      - name: maven
        run: mvn -B package --file pom.xml
